version: '3.4'

services:
  configuration.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  service-a:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  service-b:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  service-c:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

